name: shoping
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  get: ^3.22.2
  google_sign_in: ^4.5.6
  firebase_core: "0.5.3"
  firebase_auth: "^0.18.4"
  cloud_firestore: "^0.14.4"
  flutter_facebook_auth: "^1.0.0"
  flutter_facebook_login: ^3.0.0
  sqflite: ^2.0.0+3
  path: ^1.8.0
  shared_preferences: ^2.0.5
  flutter_svg: ^0.19.0
  status_change: ^1.0.0




dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/i_healthy.png"

flutter:

  uses-material-design: true


  assets:
    - assets/images/
    - assets/fonts/
    - assets/menu_icon/


  fonts:
    - family: SourceSans
      fonts:
        - asset: assets/fonts/SourceSansPro.ttf
